#!/usr/bin/env python3
"""
Experience Monitor - Detect missing experience logs and auto-backfill
"""

import os
import json
from datetime import datetime, timedelta
from pathlib import Path

# Config
STATE_FILE = "/home/ubuntu/health-monitors/state/experience_state.json"
LOG_FILE = "/home/ubuntu/health-monitors/logs/experience_monitor.log"
EXPERIENCE_DIR = "/home/ubuntu/.openclaw/workspace/memory/experiences"

def ensure_dirs():
    Path(STATE_FILE).parent.mkdir(parents=True, exist_ok=True)
    Path(LOG_FILE).parent.mkdir(parents=True, exist_ok=True)

def log(msg):
    ensure_dirs()
    timestamp = datetime.now().isoformat()
    entry = f"[{timestamp}] {msg}"
    print(entry)
    with open(LOG_FILE, "a") as f:
        f.write(entry + "\n")

def check_experience_logs():
    """Check for missing experience logs"""
    today = datetime.now()
    issues = []
    
    # Check last 7 days
    for i in range(7):
        check_date = today - timedelta(days=i)
        date_str = check_date.strftime("%Y-%m-%d")
        exp_file = os.path.join(EXPERIENCE_DIR, f"{date_str}.jsonl")
        
        if not os.path.exists(exp_file):
            issues.append({
                "date": date_str,
                "type": "missing_file",
                "severity": "low" if i > 2 else "medium"
            })
        else:
            # Check if file is empty
            size = os.path.getsize(exp_file)
            if size == 0:
                issues.append({
                    "date": date_str,
                    "type": "empty_file",
                    "severity": "low"
                })
    
    return issues

def backfill_experience(date_str):
    """Create a placeholder experience log for a missing date"""
    try:
        Path(EXPERIENCE_DIR).mkdir(parents=True, exist_ok=True)
        
        placeholder = {
            "timestamp": datetime.now().isoformat(),
            "date": date_str,
            "task_type": "monitor_check",
            "approach": "auto_backfill",
            "outcome": "no_data",
            "note": "Auto-generated by experience_monitor - no tasks logged this day"
        }
        
        exp_file = os.path.join(EXPERIENCE_DIR, f"{date_str}.jsonl")
        with open(exp_file, "a") as f:
            f.write(json.dumps(placeholder) + "\n")
        
        return True
    except Exception as e:
        log(f"Error backfilling {date_str}: {e}")
        return False

def check():
    """Main check function"""
    issues = check_experience_logs()
    
    state = {
        "timestamp": datetime.now().isoformat(),
        "issues_found": len(issues),
        "issues": issues,
        "status": "healthy",
        "backfilled": []
    }
    
    if issues:
        # Backfill missing files
        for issue in issues:
            if issue["type"] == "missing_file":
                if backfill_experience(issue["date"]):
                    state["backfilled"].append(issue["date"])
        
        # Determine status
        critical_issues = [i for i in issues if i.get("severity") == "high"]
        warning_issues = [i for i in issues if i.get("severity") in ["medium", "low"]]
        
        if critical_issues:
            state["status"] = "critical"
        elif warning_issues:
            state["status"] = "warning"
    
    # Save state
    ensure_dirs()
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=2)
    
    log(f"Experience logs: {len(issues)} issues, {len(state['backfilled'])} backfilled - Status: {state['status']}")
    return state

if __name__ == "__main__":
    check()
